-- =========================================================
-- 003 — Seed the recipe vault with Elisa's 216 historical dishes
-- (from her spreadsheet; names + categories only, no instructions yet).
-- Safe to re-run: existing ids are skipped.
-- =========================================================

insert into public.recipe_vault (id, name, category, times_used)
values
    ('vault_elisa_1', 'Blanquette de poulet revisitée', 'viande', 1),
    ('vault_elisa_2', 'Parmentier de confit de canard', 'viande', 1),
    ('vault_elisa_3', 'Dahl de lentilles de corail coco, kale et cheese naan maison', 'Végétarien', 1),
    ('vault_elisa_4', 'Velouté de butternut, noisettes et grilled cheese comté, épinard', 'Végétarien', 1),
    ('vault_elisa_5', 'Crumble salé aux légumes d''hiver, feta et noix', 'Végétarien', 1),
    ('vault_elisa_6', 'Truite aux herbes et câpres, purée et carottes glacées', 'Poisson', 1),
    ('vault_elisa_7', 'Crevettes sautées à l’ail et moutarde, riz parfumé, carottes vichy', 'Poisson', 1),
    ('vault_elisa_8', 'Tarte fine aux légumes d''hiver', 'Végan', 1),
    ('vault_elisa_9', 'Canard à l’orange, polenta crémeuse et champignons aux herbes', 'viande', 1),
    ('vault_elisa_10', 'Bœuf bourguignon léger et pommes vapeur', 'viande', 1),
    ('vault_elisa_11', 'Soupe champignons, marrons et grilled cheese oignon confit et fromage à raclette', 'Végétarien', 1),
    ('vault_elisa_12', 'Risotto asperges et champignons, parmesan & amandes torréfiées', 'Végétarien', 1),
    ('vault_elisa_13', 'Falafels maison, sauce tahini et polenta crémeuse', 'Végétarien', 1),
    ('vault_elisa_14', 'Lieu noir sauce moutarde, haricots à l’ail et patatas bravas', 'Poisson', 1),
    ('vault_elisa_15', 'Cabillaud sauce coco-curry doux, légumes et riz basmati', 'Poisson', 1),
    ('vault_elisa_16', 'Tian de légumes d''hiver, fromage végan', 'Végan', 1),
    ('vault_elisa_17', 'Tarte tatin poireaux, fêta, thon', 'Poisson', 1),
    ('vault_elisa_18', 'Risotto de topinambour, noisettes torréfiée, parmesan', 'Végétarien', 1),
    ('vault_elisa_19', 'Filet mignon, sauce à la bière et moutarde, purée de panais', 'viande', 1),
    ('vault_elisa_20', 'Ballottines de poulet au jambon sec, sauce aux champignons, riz pilaf', 'viande', 1),
    ('vault_elisa_21', 'Gnocchis maison, shiitaké fondant et parmesan', 'Végétarien', 1),
    ('vault_elisa_22', 'Velouté chou-fleur et chorizo, éclat de noisettes', 'Végétarien', 1),
    ('vault_elisa_23', 'Aile de raie au court-bouillon, sauce aux agrumes d’hiver et carottes glacées', 'Poisson', 1),
    ('vault_elisa_24', 'Filet de merlan en croûte d’herbes & citron, petits légumes verts sautés', 'Poisson', 1),
    ('vault_elisa_25', 'Cordon bleu façon banger, frites de patate douce', 'viande', 1),
    ('vault_elisa_26', 'Quiche au chèvre et aux poires', 'Végétarien', 1),
    ('vault_elisa_27', 'Falafels, sauce yaourt et orzo à la méditerranéenne', 'Végétarien', 1),
    ('vault_elisa_28', 'Velouté de poireaux, avec son grilled cheese épinard', 'Végétarien', 1),
    ('vault_elisa_29', 'Filets de saumon, sauce à la crème d’estragon et purée de céleri-rave', 'Poisson', 1),
    ('vault_elisa_30', 'Risotto d''épeautre, champignons et oignons caramélisés', 'Végétarien', 1),
    ('vault_elisa_31', 'Shawarma d''agneau avec marinade et légumes d''hiver', 'viande', 1),
    ('vault_elisa_32', 'Pizza poireaux fondants, courge rôtie, comté & thym', 'Végétarien', 1),
    ('vault_elisa_33', 'Filets de merlu, sauce curry coco et coriandre', 'Poisson', 1),
    ('vault_elisa_34', 'Poireaux braisés, houmous tiède, épeautre au citron et noisettes grillées', 'Végan', 1),
    ('vault_elisa_35', 'Boudin noir, pomme cannelle, purée de pomme de terre', 'viande', 1),
    ('vault_elisa_36', 'Tourte de légumes à l''irlandaise', 'Végétarien', 1),
    ('vault_elisa_37', 'Cocotte de légumes d''hiver, châtaignes et quinoa', 'Végétarien', 1),
    ('vault_elisa_38', 'Dos de lieu noir, tombée d''épinards au lait de coco et quinoa', 'Poisson', 1),
    ('vault_elisa_39', 'Truite laquée soja, miel & gingembre et topinambour rôti, haricots verts', 'Poisson', 1),
    ('vault_elisa_40', 'Galettes croustillantes de panais & pois chiches, salade tiède de chou', 'Végan', 1),
    ('vault_elisa_41', 'Porc fondant au caramel, choux de Bruxelles rôtis & carottes et panais dorés', 'viande', 1),
    ('vault_elisa_42', 'Rigatoni sauce au bleu, épinards & champignons', 'Végétarien', 1),
    ('vault_elisa_43', 'Quiche ricotta, épinards et olives', 'Végétarien', 1),
    ('vault_elisa_44', 'Curry de patates douces, lentilles et pois chiches', 'Végan', 1),
    ('vault_elisa_45', 'Parmentier de haddock, patate douce & fondue de poireaux', 'Poisson', 1),
    ('vault_elisa_46', 'Steak de chou-fleur rôti, purée de panais & sauce tahini-citron', 'Végan', 1),
    ('vault_elisa_47', 'Ballotines de poulet farcies aux marrons et frites de patate douce', 'viande', 1),
    ('vault_elisa_48', 'Boulettes d’agneau aux épices douces, asperges et yaourt aux herbes', 'viande', 1),
    ('vault_elisa_49', 'Brownie salé épinard-feta', 'Végétarien', 1),
    ('vault_elisa_50', 'Friands au céleri-rave, pomme et noisette et patates au paprika', 'Végétarien', 1),
    ('vault_elisa_51', 'Parmentier de haddock, purée de pomme de terre & fondue de poireaux', 'Poisson', 1),
    ('vault_elisa_52', 'Blanquette de la mer aux crustacés', 'Poisson', 1),
    ('vault_elisa_53', 'Tarte fine aux oignons confits, blettes & crème d’amande', 'Végan', 1),
    ('vault_elisa_54', 'Saucisson brioché maison, salade de lentilles fraîches', 'viande', 1),
    ('vault_elisa_55', 'Mafé revisité poulet, cacahuètes & gingembre, riz coco, légumes rôtis', 'viande', 1),
    ('vault_elisa_56', 'Tarte tatin de poireaux, fêta et crème citronnée', 'Végétarien', 1),
    ('vault_elisa_57', 'Vol-au-vent végé, champignons à la crème & asperges vertes', 'Végétarien', 1),
    ('vault_elisa_58', 'Patate douce farcie à la mexicaine', 'Végétarien', 1),
    ('vault_elisa_59', 'Maquereau grillé, fenouil confit, pommes rôties & grenaille, yaourt citron-aneth', 'Poisson', 1),
    ('vault_elisa_60', 'Tofu au curry coco et carottes, naan vegan maison', 'Végan', 1),
    ('vault_elisa_61', 'Empanadas maison au bœuf, coleslaw citron vert & herbes fraîches', 'viande', 1),
    ('vault_elisa_62', 'Bavette à l’échalote, purée de pomme de terre', 'viande', 1),
    ('vault_elisa_63', 'Risotto au cresson, noisettes torréfiées & œuf mollet', 'Végétarien', 1),
    ('vault_elisa_64', 'Quiche aux trois fromages ultra crémeuse', 'Végétarien', 1),
    ('vault_elisa_65', 'Blanquette végétarienne de légumes racines & haricots blancs', 'Végétarien', 1),
    ('vault_elisa_66', 'Brandade de morue maison', 'Poisson', 1),
    ('vault_elisa_67', 'Travers de porc confit, laque miel et moutarde, et légumes fondants', 'viande', 1),
    ('vault_elisa_68', 'Poulet aux pois gourmands, polenta crémeuse', 'viande', 1),
    ('vault_elisa_69', 'Crumble de chou-fleur & pois chiches au parmesan et noisettes', 'Végétarien', 1),
    ('vault_elisa_70', 'Croque-monsieur à l''ail des ours et fondue de poireaux, taboulé de persil aux amandes', 'Végétarien', 1),
    ('vault_elisa_71', 'Curry d''épinards et de pommes de terre, pain cheese naan maison', 'Végétarien', 1),
    ('vault_elisa_72', 'Penne aux crevettes et à la coriandre', 'Poisson', 1),
    ('vault_elisa_73', 'Croquettes de patate douce et reblochon pané, saumon snacké', 'Poisson', 1),
    ('vault_elisa_74', 'Wok de tofu mariné, brocolis croquants et infusion de coco au gingembre', 'Végan', 1),
    ('vault_elisa_75', 'Tajine de poulet à la marocaine aux citrons confits', 'viande', 1),
    ('vault_elisa_76', 'Sauté d''agneau au curry, semoule aux fruits secs & carottes rôties', 'viande', 1),
    ('vault_elisa_77', 'Pizza printanière, asperges, ricotta et pesto d''ail des ours', 'Végétarien', 1),
    ('vault_elisa_78', 'Orzotto aux morilles, ail nouveau & parmesan', 'Végétarien', 1),
    ('vault_elisa_79', 'Cake printanier (feta, noix, épinard) et tartare de betterave à l''aneth', 'Végétarien', 1),
    ('vault_elisa_80', 'Millefeuille de pommes de terre, cabillaud, crème citronnée au yaourt', 'Poisson', 1),
    ('vault_elisa_81', 'Dos de merlu en papillote, écrasé de grenailles et fèves fraîches à la menthe', 'Poisson', 1),
    ('vault_elisa_82', 'Linguine à la bolognaise de lentilles Beluga, épinards frais et éclats de noix', 'Végan', 1),
    ('vault_elisa_83', 'Bœuf sauté façon Lok Lak et son riz rouge à l’ail, légumes croquants', 'viande', 1),
    ('vault_elisa_84', 'Filet mignon en croûte, jardinière de jeunes légumes infusée à la menthe', 'viande', 1),
    ('vault_elisa_85', 'Carpaccio de betterave, pommes vertes et noix & smashed potatoes croustillantes', 'Végétarien', 1),
    ('vault_elisa_86', 'Bun burger maison, bacon végétal, oignons caramélisés, raclette & frites au paprika', 'Végétarien', 1),
    ('vault_elisa_87', 'Clafoutis salé aux poireaux et Comté affiné, salade de lentilles à l''ancienne', 'Végétarien', 1),
    ('vault_elisa_88', 'Quinoa aux herbes, crevettes saisies au chorizo et fèves de printemps', 'Poisson', 1),
    ('vault_elisa_89', 'Pavé de saumon à l''oseille fraîche, escorté d''asperges blanches fondantes', 'Poisson', 1),
    ('vault_elisa_90', 'Soba froides au beurre de cacahuète et jeunes poireaux', 'Végan', 1),
    ('vault_elisa_91', 'Côte de bœuf marinée du boucher & salade de fenouil braisé à l''orange', 'viande', 1),
    ('vault_elisa_92', 'Poulet coco curry vert, vermicelles et légumes croquants printaniers', 'viande', 1),
    ('vault_elisa_93', 'Socca-pizza au crémeux de ricotta citronné, asperges vertes et oignons fondants', 'Végétarien', 1),
    ('vault_elisa_94', 'Brique artichaut-parmesan-olive & salade de lentilles aux tomates rôties', 'Végétarien', 1),
    ('vault_elisa_95', 'Clafoutis à la ratatouille & fromage de brebis', 'Végétarien', 1),
    ('vault_elisa_96', 'Dos de cabillaud façon blanquette printanière', 'Poisson', 1),
    ('vault_elisa_97', 'Brochettes de crevettes & courgettes, quinoa aux herbes', 'Poisson', 1),
    ('vault_elisa_98', 'Shakshuka verte avec asperges, épinards et tofu soyeux', 'Végan', 1),
    ('vault_elisa_99', 'Courgettes farcies au bœuf, sauce tomate et parmesan & riz tomate estragon', 'viande', 1),
    ('vault_elisa_100', 'Suprême de volaille sauce moutarde à l’ancienne, pommes de terre suédoises', 'viande', 1),
    ('vault_elisa_101', 'Lasagnes ouvertes aux asperges, ricotta citronnée et pesto d’herbes', 'Végétarien', 1),
    ('vault_elisa_102', 'Cake salé aux tomates séchées, parmesan & coleslaw au fenouil et radis', 'Végétarien', 1),
    ('vault_elisa_103', 'Tartare de truite aux radis et concombre croquants, blinis et crème aneth', 'Poisson', 1),
    ('vault_elisa_104', 'Filet de maquereau à la rhubarbe, dahl de lentilles corail au coco et cumin', 'Poisson', 1),
    ('vault_elisa_105', 'Pièce du boucher, sauce roquefort, écrasé de pommes de terre à l’huile d’olive', 'viande', 1),
    ('vault_elisa_106', 'Lapin rôti à la moutarde, légumes de printemps rôtis', 'viande', 1),
    ('vault_elisa_107', 'Risotto vert aux petits pois, menthe et pecorino', 'Végétarien', 1),
    ('vault_elisa_108', 'Orzotto de courgettes, citron, parmesan & noisettes torréfiées', 'Végétarien', 1),
    ('vault_elisa_109', 'Millefeuille de légumes rôtis, chèvre frais et pesto fanes de carottes', 'Végétarien', 1),
    ('vault_elisa_110', 'Parmentier de merlu, asperges vertes et crème d’oseille', 'Poisson', 1),
    ('vault_elisa_111', 'Saint-Jacques snackées, purée de carottes aux épices et chou-fleur rôti', 'Poisson', 1),
    ('vault_elisa_112', 'Asperges braisées, houmous tiède, épeautre au citron et noisettes grillées', 'Végan', 1),
    ('vault_elisa_113', 'Poulet aux olives à la méditerranéenne, semoule parfumée et éclats d''amandes', 'viande', 1),
    ('vault_elisa_114', 'Escalope de dinde à la crème de noisettes, mousseline de céleri-rave', 'viande', 1),
    ('vault_elisa_115', 'Penne, crème de betterave, feta, noix & persil', 'Végétarien', 1),
    ('vault_elisa_116', 'Spanakopita grecque aux épinards et feta', 'Végétarien', 1),
    ('vault_elisa_117', 'Friand carotte-chèvre et sa salade de pois chiches rôtis', 'Végétarien', 1),
    ('vault_elisa_118', 'Pissaladière traditionnelle aux oignons confits, anchois et olives', 'Poisson', 1),
    ('vault_elisa_119', 'Rouleaux de printemps aux crevettes et aïoli maison, noodles au sésame', 'Poisson', 1),
    ('vault_elisa_120', 'Buddha bowl de printemps : quinoa, houmous de petits pois, tofu et épinards', 'Végan', 1),
    ('vault_elisa_121', 'Boulettes de bœuf caramélisées, écrasé de patate douce coco et citron vert', 'viande', 1),
    ('vault_elisa_122', 'Ballotine de dinde sauge & abricot, polenta onctueuse au parmesan', 'viande', 1),
    ('vault_elisa_123', 'Falafels maison aux herbes fraîches, sauce yaourt-menthe, taboulé de chou-fleur', 'Végétarien', 1),
    ('vault_elisa_124', 'Cheesecake salé au chèvre frais et herbes, base sablée au parmesan', 'Végétarien', 1),
    ('vault_elisa_125', 'Velouté de petits pois à la menthe et œuf poché', 'Végétarien', 1),
    ('vault_elisa_126', 'Dos de cabillaud en croûte de chorizo et zestes d''orange, risotto aux poireaux', 'Poisson', 1),
    ('vault_elisa_127', 'Encornets farcis à la niçoise, riz noir au citron vert', 'Poisson', 1),
    ('vault_elisa_128', 'Lasagnes aux légumes verts & béchamel au lait d''amande', 'Végan', 1),
    ('vault_elisa_129', 'Keftas de bœuf à la menthe fraîche, salade de pois chiches au sumac, feta et grenade', 'viande', 1),
    ('vault_elisa_130', 'Fondant de porc au caramel de pomme douce, grenailles et carottes fanes au miel', 'viande', 1),
    ('vault_elisa_131', 'Halloumi doré au miel & thym frais, caponata sicilienne', 'Végétarien', 1),
    ('vault_elisa_132', 'Mille-feuille de polenta grillée, courgettes et caviar de tomates séchées', 'Végétarien', 1),
    ('vault_elisa_133', 'L’Aubergine façon lasagne, haché végétal à l''origan & Mozzarella di Bufala', 'Végétarien', 1),
    ('vault_elisa_134', 'Salade de poulpe tiède, pommes de terre fondantes, tomates au four et olives', 'Poisson', 1),
    ('vault_elisa_135', 'Brochettes de lotte au lard fumé & romarin, gratin de courgettes au mascarpone', 'Poisson', 1),
    ('vault_elisa_136', 'Mijoté d''artichauts poivrade à la Barigoule, tempeh doré', 'Végan', 1),
    ('vault_elisa_137', 'Filet d''agneau en croûte et tomate séchée, salade de riz au curry', 'viande', 1),
    ('vault_elisa_138', 'Crumble de légumes rôtis, feta, olives et crumble aux amandes', 'Végétarien', 1),
    ('vault_elisa_139', 'Salade pêche snackée, patate douce rôtie, halloumi grillé, pois chiches croustillants', 'Végétarien', 1),
    ('vault_elisa_140', 'Falafels de lentilles corail aux épices douces, tzatziki de courgettes à la menthe', 'Végétarien', 1),
    ('vault_elisa_141', 'Saumon au pesto de basilic, tian de légumes d''été', 'Poisson', 1),
    ('vault_elisa_142', 'Beignets de truite, slaw croquant de fenouil et céleri, yaourt citron vert', 'Poisson', 1),
    ('vault_elisa_143', 'Orzo au pesto de roquette maison, fèves fraîches, cœurs d''artichauts et pignons', 'Végan', 1),
    ('vault_elisa_144', 'Filet mignon sauce curry vert, courgettes fondantes et polenta à la tomme', 'viande', 1),
    ('vault_elisa_145', 'Entrecôte de veau, beurre d''anchois, grenailles rôties, courgettes fondantes', 'viande', 1),
    ('vault_elisa_146', 'Tarte fine aux tomates anciennes, asperges vertes, pesto rouge et burrata', 'Végétarien', 1),
    ('vault_elisa_147', 'Shawarma végétarien aux pois chiches rôtis, légumes croquants et sauce tahini', 'Végétarien', 1),
    ('vault_elisa_148', 'Lieu noir sauce moutarde, carottes fanes rôties à l''ail et patatas bravas', 'Poisson', 1),
    ('vault_elisa_149', 'Thon snacké en croûte de sésame mariné au gingembre, jeune jardinière', 'Poisson', 1),
    ('vault_elisa_150', 'Salade tiède de betteraves rôties, lentilles parfumées et yaourt aux herbes', 'Végan', 1),
    ('vault_elisa_151', 'Poulet laqué façon Général Tao, brocolis verts et riz jasmin', 'viande', 1),
    ('vault_elisa_152', 'Magret de canard laqué au vinaigre balsamique et framboises fraîches, mousseline patate douce', 'viande', 1),
    ('vault_elisa_153', 'Flammekueche montagnarde aux oignons et reblochon', 'Végétarien', 1),
    ('vault_elisa_154', 'Croquettes de pommes de terre et petits pois, courgettes grillées, ricotta citronnée', 'Végétarien', 1),
    ('vault_elisa_155', 'Gaspacho d''été et sa bruschetta d''halloumi grillé aux pêches rôties', 'Végétarien', 1),
    ('vault_elisa_156', 'Gambas sautées à l''ail et au piment d''Espelette, semoule aux épices douces et abricots', 'Poisson', 1),
    ('vault_elisa_157', 'Dos de cabillaud en croûte d’amandes, ratatouille rôtie', 'Poisson', 1),
    ('vault_elisa_158', 'Curry vert de légumes d''été et pois chiches, boulgour aux herbes', 'Végan', 1),
    ('vault_elisa_159', 'Salade César au poulet grillé, œuf mollet, copeaux de parmesan et croûtons à l''ail', 'viande', 1),
    ('vault_elisa_160', 'Faux-filet grillé, sauce poivron-citron, écrasé de chou-fleur à l''huile d''olive', 'viande', 1),
    ('vault_elisa_161', 'Lentilles au caviar d''aubergine, tomates et sauce yaourt', 'Végétarien', 1),
    ('vault_elisa_162', 'Scones à la feta, tomates séchées, salade fraîche de melon, concombre et menthe', 'Végétarien', 1),
    ('vault_elisa_163', 'Buddha bowl d’été : quinoa, chèvre frais, tofu mariné, tomates cerises et aneth', 'Végétarien', 1),
    ('vault_elisa_164', 'Parmentier de haddock, purée de céleri-rave & fondue de poireaux', 'Poisson', 1),
    ('vault_elisa_165', 'Tartare de truite au citron vert, radis roses et cébette, crème à l’aneth', 'Poisson', 1),
    ('vault_elisa_166', 'Aubergines laquées au miso, nouilles soba et concombre au sésame', 'Végan', 1),
    ('vault_elisa_167', 'Filet mignon façon orloff à la coppa, mozzarella et poêlée de haricots verts', 'viande', 1),
    ('vault_elisa_168', 'Aiguillettes de poulet panées aux graines, frites de carottes et sauce creamy', 'viande', 1),
    ('vault_elisa_169', 'Keftas de lentilles corail à la feta, grenailles croustillantes et sauce blanche', 'Végétarien', 1),
    ('vault_elisa_170', 'Salade de riz parfumée à la menthe, grenade, feta, noix et olives', 'Végétarien', 1),
    ('vault_elisa_171', 'Tacos aux croquettes de poisson croustillantes, slaw croquant au chou rouge', 'Poisson', 1),
    ('vault_elisa_172', 'Curry de patates douces, pois chiches et lait de coco, graines de courge', 'Végan', 1),
    ('vault_elisa_173', 'Pavé du boucher mariné à l''ail confit, gratin de pommes de terre', 'viande', 1),
    ('vault_elisa_174', 'Clafoutis estival aux tomates cerises, feta & origan, mesclun aux noix', 'Végétarien', 1),
    ('vault_elisa_175', 'Boulgour à la tomate, aux aubergines et au yaourt citronné', 'Végétarien', 1),
    ('vault_elisa_176', 'Velouté de maïs doux au piment d''Espelette, œuf poché coulant', 'Végétarien', 1),
    ('vault_elisa_177', 'Pavé de saumon, crème à l''aneth, polenta crémeuse au parmesan et poivrons doux', 'Poisson', 1),
    ('vault_elisa_178', 'Tatin d''aubergines confites au balsamique, tapenade de tomates', 'Végan', 1),
    ('vault_elisa_179', 'Vitello tonnato, et sa salade estivale de haricots verts, tomates cerises & basilic', 'viande', 1),
    ('vault_elisa_180', 'Salade "Spring Roll" déstructurée au porc caramélisé & sauce cacahuète', 'viande', 1),
    ('vault_elisa_181', 'Galettes de maïs frais, cheddar & ciboulette, compotée de tomates au basilic', 'Végétarien', 1),
    ('vault_elisa_182', 'Maquereau façon teriyaki, aubergines grillées & riz japonais', 'Poisson', 1),
    ('vault_elisa_183', 'Poivrons farcis au boulgour, pois chiches & raisins secs', 'Végan', 1),
    ('vault_elisa_184', 'Mini-courgettes farcies à la ricotta, citron & menthe sur lit de boulgour', 'Végétarien', 1),
    ('vault_elisa_185', 'Gaspacho de melon, concombre, poivron et bruschetta d''halloumi grillé', 'Végétarien', 1),
    ('vault_elisa_186', 'Empanadas au maïs, poivrons & fromage, salsa Pico de Gallo aux pêches', 'Végétarien', 1),
    ('vault_elisa_187', 'Parmentier de cabillaud, poireaux et patate douce', 'Poisson', 1),
    ('vault_elisa_188', 'Paëlla traditionnelle d''été au poulet doré, calamars, crevettes et riz safrané', 'Poisson', 1),
    ('vault_elisa_189', 'Tian de légumes d''été au pesto de basilic maison, socca croustillante', 'Végan', 1),
    ('vault_elisa_190', 'Effiloché de porc aux épices douces, écrasé de patate douce coco et oignons frits', 'viande', 1),
    ('vault_elisa_191', 'Tarte tatin de tomates au balsamique, oignons confits, mozzarella et burrata', 'Végétarien', 1),
    ('vault_elisa_192', 'Crumble croustillant aux graines, poivrons & aubergines confites, feta fouettée', 'Végétarien', 1),
    ('vault_elisa_193', 'Galettes de courgettes feta et menthe, tzatziki et salade de pois chiches', 'Végétarien', 1),
    ('vault_elisa_194', 'Tataki de thon mariné à la verveine & citron, haricots verts, pêche et noisettes', 'Poisson', 1),
    ('vault_elisa_195', 'Pavé de saumon en croûte d''amandes, crémeux de maïs au citron vert et courgettes', 'Poisson', 1),
    ('vault_elisa_196', 'Fatayers chèvre, miel et oignon fondant avec sa salade Fattouche d''été', 'Végétarien', 1),
    ('vault_elisa_197', 'Mini-courgettes farcies à la feta fouettée, tomates séchées & noisettes, riz basmati', 'Végétarien', 1),
    ('vault_elisa_198', 'Cheesecake d''été au chèvre, poivrons rôtis sur sablé au parmesan', 'Végétarien', 1),
    ('vault_elisa_199', 'Filet de maquereau, sauce vierge pistache, orzo sauté aux tomates cerises', 'Poisson', 1),
    ('vault_elisa_200', 'Croquettes de poisson croustillantes, salade de grenailles aux herbes, tartare légère', 'Poisson', 1),
    ('vault_elisa_201', 'Aubergines laquées au miso doux, quinoa aux herbes et sauce crémeuse au tahini', 'Végan', 1),
    ('vault_elisa_202', 'Bavette grillée & sa sauce au poivre, gratin de courgettes fondues', 'viande', 1),
    ('vault_elisa_203', 'Quesadillas aux poivrons grillés, maïs frais, haricots rouges & cheddar', 'Végétarien', 1),
    ('vault_elisa_204', 'Halloumi grillé & son taboulé oriental de lentilles aux tomates, persil & menthe', 'Végétarien', 1),
    ('vault_elisa_205', 'Croquettes de Saint-Marcellin coulant, salade fraîcheur de tomates et pêches', 'Végétarien', 1),
    ('vault_elisa_206', 'Tartare de truite, sauce aneth-citron et pommes de terre grenailles rôties', 'Poisson', 1),
    ('vault_elisa_207', 'Dos de cabillaud rôti & vierge de tomates au basilic, orzo façon risotto', 'Poisson', 1),
    ('vault_elisa_208', 'Falafels maison, taboulé de quinoa aux herbes & sauce tahini citronnée', 'Végan', 1),
    ('vault_elisa_209', 'Boulettes de bœuf à la méditerranéenne, semoule aux herbes & sauce yaourt citronnée', 'viande', 1),
    ('vault_elisa_210', 'Poulet à la moutarde avec son gratin dauphinois', 'viande', 1),
    ('vault_elisa_211', 'Muffins moelleux au Roquefort, tomates séchées & noix, roquette aux noix', 'Végétarien', 1),
    ('vault_elisa_212', 'Cordon bleu d''aubergine panée, mozzarella & tomates séchées, purée de pommes de terre', 'Végétarien', 1),
    ('vault_elisa_213', 'Risotto d''épeautre à la crème de carottes rôties au cumin, noisettes & persil', 'Végétarien', 1),
    ('vault_elisa_214', 'Dos de Lieu Noir en croûte d''herbes & parmesan, tian de légumes d''été', 'Poisson', 1),
    ('vault_elisa_215', 'Moqueca brésilienne : Mijoté de poisson blanc & crevettes coco, poivrons et riz', 'Poisson', 1),
    ('vault_elisa_216', 'Risotto de petit épeautre d''été aux maïs rôti, poivrons doux & basilic frais', 'Végétarien', 1)
on conflict do nothing;
